name: flutter_webview_example
description: Demonstrates how to use the flutter_webview plugin.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_webview:
    path: ../

flutter:
  uses-material-design: true